# Generated by Django 3.0.2 on 2020-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('shoptitle', models.TextField(blank=True, db_column='shopTitle', null=True)),
                ('shoplink', models.TextField(blank=True, db_column='ShopLink', null=True)),
                ('field_imglink', models.TextField(blank=True, db_column=' imgLink', null=True)),
            ],
            options={
                'db_table': 'theater_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TheaterDf',
            fields=[
                ('theater_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('startdate', models.TextField(blank=True, null=True)),
                ('enddate', models.TextField(blank=True, null=True)),
                ('openrun', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'theater_df',
                'managed': False,
            },
        ),
    ]
